/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package bbs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import bbs.biz.TopicBiz;
import bbs.struts.form.TipForm;

public class DeleteTipAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TipForm tipForm = (TipForm) form;
		
		TopicBiz topicBiz = new TopicBiz();
		
		if (topicBiz.deleteTopic(tipForm.getTopicId())) {
			return mapping.findForward("DeleteTopicTipSuccess");
		}
			return mapping.findForward("DeleteTopicTipFailure");
	}
}