/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package bbs.struts.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import bbs.biz.UserBiz;
import bbs.entity.User;
import bbs.struts.form.UserForm;

public class LoginAction extends DispatchAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;

		String userName = userForm.getUserName(); //获取用户名
		String userPwd = userForm.getUserPwd(); //获取密码

		UserBiz userBiz = new UserBiz();
		HttpSession session = request.getSession(); //创建session对象实例
		
		User user = (User)session.getAttribute("LoginedUser"); //获取session中的登录用户
		if (user != null) { //判断session是否包含用户
			session.removeAttribute("LoginedUser"); //删除session已存在的登录用户
		}
		
		user = userBiz.doLogin(userName, userPwd);
		if (user != null) {
			session.setAttribute("LoginedUser", user); //保存用户信息到session
			return mapping.findForward("logined"); //跳转到首页
		} else {
			return mapping.findForward("failure");
		}

	}
}