/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package bbs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import bbs.biz.ReplyBiz;
import bbs.struts.form.TipForm;

public class NewReplyAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) {
		TipForm tipForm = (TipForm) form;
		
		ReplyBiz replyBiz = new ReplyBiz();
		
		if (replyBiz.addReply(tipForm.getReply())) {
			return mapping.findForward("NewReplySuccess");
		}
			return mapping.findForward("NewReplyFailure");
	}
}