/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package bbs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import bbs.biz.BoardBiz;
import bbs.biz.TopicBiz;
import bbs.struts.form.TipForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-24-2016
 * 
 * XDoclet definition:
 * @struts.action path="/toTopicListAction" name="tipForm" scope="request"
 */
public class ToTopicListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TipForm tipForm = (TipForm) form;
		
		int boardId = tipForm.getBoard().getBoardId();		
		int page = tipForm.getPage();	
		
		BoardBiz boardBiz = new BoardBiz();
		TopicBiz topicBiz = new TopicBiz();
		
		tipForm.setBoard(boardBiz.findBoardById(boardId));
		tipForm.setPageCount((topicBiz.findCountTopic(boardId)+9)/10);
		request.setAttribute("topicList", topicBiz.findTopicList(page, boardId));
		
		return mapping.findForward("topicList");
	}
}