/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package bbs.struts.form;

import org.apache.struts.action.ActionForm;


@SuppressWarnings("serial")
public class UserForm extends ActionForm {
	
	private String userName;
	private String userPwd;
	private String head;
	private boolean gender;
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getUserPwd() {
		return userPwd;
	}
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}
	public String getHead() {
		return head;
	}
	public void setHead(String head) {
		this.head = head;
	}
	public boolean isGender() {
		return gender;
	}
	public void setGender(boolean gender) {
		this.gender = gender;
	}
	public UserForm(String userName, String userPwd, String head, boolean gender) {
		super();
		this.userName = userName;
		this.userPwd = userPwd;
		this.head = head;
		this.gender = gender;
	}
	public UserForm() {
		super();
	}
}